name: Tests

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.3
          architecture: x64
      - name: Show path
        run: |
          pwd
          ls