name: Tests

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  django-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install -e .
          python -m pip install -r ./requirements.txt
      - name: Run tests
        run: |
          python ./tests.py